version: '2'
services:
  slight:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000" # specify port forewarding
    volumes:
    - .:/home/app
    - /home/node_modules
    environment:
    - NODE_ENV
